FROM mariadb:10.6.17

ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=testdatabase
ENV MYSQL_USER=testuser
ENV MYSQL_PASSWORD=testpassword

EXPOSE 3306

VOLUME /var/lib/docker/volumes/db_backups

